### ISSUE TITLE
My Todo List

### ISSUE THREAD

**Issue by Geobert** [antimoine-org/antimoine#1]
- [ ] add `schedule` from emile (*Nix only)
- [ ] add `unschedule` from emile (*Nix only)
- [ ] add `git-hook` from emile (*Nix only)
- [ ] add `publish-flow` from emile (*Nix only)
- [ ] add `year shift` for `new` command like in emile
- [ ] add `reslug` from emile
- [ ] setup Azure pipeline
  - [ ] release on tags
  - [ ] add `commited`
- [ ] add live reload for `serve`
- [ ] documentation
